# A docker compose file with postgres database
services:
  db:
    image: postgres:17-alpine3.20
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data