# Generated by Django 5.1.3 on 2024-11-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('transaction_date', models.DateTimeField()),
                ('customer_id', models.IntegerField()),
                ('account_id', models.IntegerField()),
                ('schedule_id', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
