# Generated by Django 5.1.3 on 2024-11-13 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_servicemanager_role'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='customeraccount',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
            preserve_default=False,
        ),
    ]
